INSERT INTO Seasons VALUES 
	(2015);

INSERT INTO team (name) VALUES 
	('Real Madrid'),
	('Barcelona'),
	('Atlético Madrid'),
	('Betis'),
	('Celta Vigo'),
	('Deportivo La Coruña'),
	('Eibar'),
	('Espanyol'),
	('Getafe'),
	('Granada'),
	('Las Palmas'),
	('Levante'),
	('Málaga'),
	('Rayo Vallecano'),
	('Real Sociedad'),
	('Sevilla'),
	('Sporting de Gijón'),
	('Valencia'),
	('Villarreal'),
	('Athletic Bilbao');
	
INSERT INTO Player (playernr, team, name) VALUES
	(1, 'Real Madrid', 'Keylor Navas'),
	(2, 'Real Madrid', 'Raphaël Varane'),
	(3, 'Real Madrid', 'Pepe'),
	(4, 'Real Madrid', 'Sergio Ramos'),
	(6, 'Real Madrid', 'Nacho'),
	(7, 'Real Madrid', 'Cristiano Ronaldo'),
	(8, 'Real Madrid', 'Toni Kroos'),
	(9, 'Real Madrid', 'Karim Benzema'),
	(10, 'Real Madrid', 'James Rodríguez'),
	(11, 'Real Madrid', 'Gareth Bale'),
	(12, 'Real Madrid', 'Marcelo'),
	(13, 'Real Madrid', 'Kiko Casilla'),
	(14, 'Real Madrid', 'Casemiro'),
	(15, 'Real Madrid', 'Dani Carvajal'),
	(16, 'Real Madrid', 'Mateo Kovačić'),
	(17, 'Real Madrid', 'Álvaro Arbeloa'),
	(18, 'Real Madrid', 'Lucas Vázquez'),
	(19, 'Real Madrid', 'Luka Modrić'),
	(20, 'Real Madrid', 'Jesé'),
	(22, 'Real Madrid', 'Isco'),
	(23, 'Real Madrid', 'Danilo'),
	(31, 'Real Madrid', 'Rubén Yáñez'),
	
	(1, 'Barcelona', 'Marc-André ter Stegen'),
	(2, 'Barcelona', 'Douglas'),
	(3, 'Barcelona', 'Gerard Piqué'),
	(4, 'Barcelona', 'Ivan Rakitić'),
	(5, 'Barcelona', 'Sergio Busquets'),
	(6, 'Barcelona', 'Dani Alves'),
	(7, 'Barcelona', 'Arda Turan'),
	(8, 'Barcelona', 'Andrés Iniesta'),
	(9, 'Barcelona', 'Luis Suárez'),
	(10, 'Barcelona', 'Lionel Messi'),
	(11, 'Barcelona', 'Neymar'),
	(12, 'Barcelona', 'Rafinha'),
	(13, 'Barcelona', 'Claudio Bravo'),
	(14, 'Barcelona', 'Javier Mascherano'),
	(15, 'Barcelona', 'Marc Bartra'),
	(17, 'Barcelona', 'Munir El Haddadi'),
	(18, 'Barcelona', 'Jordi Alba'),
	(19, 'Barcelona', 'Sandro Ramírez'),
	(20, 'Barcelona', 'Sergi Roberto'),
	(21, 'Barcelona', 'Adriano'),
	(22, 'Barcelona', 'Aleix Vidal'),
	(23, 'Barcelona', 'Thomas Vermaelen')
	(24, 'Barcelona', 'Jérémy Mathieu'),
	(25, 'Barcelona', 'Jordi Masip');